# Generated by Django 4.0.4 on 2022-04-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bledevices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledevices.bledevicetype')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bledevices.bledevice')),
            ],
        ),
    ]
